export const doctorCategories = [
  { id: "gp", title: "General Practitioner" },
  { id: "cardio", title: "Cardiologist" },
  { id: "derma", title: "Dermatologist" },
  { id: "neuro", title: "Neurologist" },
  { id: "pedia", title: "Pediatrician" },
  { id: "psych", title: "Psychiatrist" },
  { id: "radio", title: "Radiologist" },
  { id: "surgeon", title: "Surgeon" },
];

export const nurseCategories = [
  { id: "rn", title: "Registered Nurse" },
  { id: "en", title: "Enrolled Nurse" },
  { id: "cn", title: "Clinical Nurse" },
  { id: "np", title: "Nurse Practitioner" },
  { id: "an", title: "Anaesthetic Nurse" },
  { id: "er", title: "Emergency Room Nurse" },
  { id: "icu", title: "ICU Nurse" },
  { id: "midwife", title: "Midwife" },
];

export const phoneCodes = [
  { code: "+27", label: "South Africa (+27)" },
  { code: "+213", label: "Algeria (+213)" },
  { code: "+244", label: "Angola (+244)" },
  { code: "+229", label: "Benin (+229)" },
  { code: "+226", label: "Burkina Faso (+226)" },
  { code: "+257", label: "Burundi (+257)" },
  { code: "+237", label: "Cameroon (+237)" },
  { code: "+238", label: "Cape Verde (+238)" },
  { code: "+236", label: "Central African Republic (+236)" },
  { code: "+235", label: "Chad (+235)" },
  { code: "+269", label: "Comoros (+269)" },
  { code: "+243", label: "Congo, Democratic Republic (+243)" },
  { code: "+242", label: "Congo, Republic (+242)" },
  { code: "+225", label: "Côte d'Ivoire (+225)" },
  { code: "+253", label: "Djibouti (+253)" },
  { code: "+20", label: "Egypt (+20)" },
  { code: "+240", label: "Equatorial Guinea (+240)" },
  { code: "+291", label: "Eritrea (+291)" },
  { code: "+251", label: "Ethiopia (+251)" },
  { code: "+241", label: "Gabon (+241)" },
  { code: "+220", label: "Gambia (+220)" },
  { code: "+233", label: "Ghana (+233)" },
  { code: "+224", label: "Guinea (+224)" },
  { code: "+245", label: "Guinea-Bissau (+245)" },
  { code: "+254", label: "Kenya (+254)" },
  { code: "+266", label: "Lesotho (+266)" },
  { code: "+231", label: "Liberia (+231)" },
  { code: "+218", label: "Libya (+218)" },
  { code: "+261", label: "Madagascar (+261)" },
  { code: "+265", label: "Malawi (+265)" },
  { code: "+223", label: "Mali (+223)" },
  { code: "+222", label: "Mauritania (+222)" },
  { code: "+230", label: "Mauritius (+230)" },
  { code: "+212", label: "Morocco (+212)" },
  { code: "+258", label: "Mozambique (+258)" },
  { code: "+264", label: "Namibia (+264)" },
  { code: "+227", label: "Niger (+227)" },
  { code: "+234", label: "Nigeria (+234)" },
  { code: "+250", label: "Rwanda (+250)" },
  { code: "+239", label: "Sao Tome and Principe (+239)" },
  { code: "+221", label: "Senegal (+221)" },
  { code: "+248", label: "Seychelles (+248)" },
  { code: "+232", label: "Sierra Leone (+232)" },
  { code: "+252", label: "Somalia (+252)" },
  { code: "+211", label: "South Sudan (+211)" },
  { code: "+249", label: "Sudan (+249)" },
  { code: "+268", label: "Eswatini (+268)" },
  { code: "+255", label: "Tanzania (+255)" },
  { code: "+228", label: "Togo (+228)" },
  { code: "+216", label: "Tunisia (+216)" },
  { code: "+256", label: "Uganda (+256)" },
  { code: "+260", label: "Zambia (+260)" },
  { code: "+263", label: "Zimbabwe (+263)" },
];

export const africanCountries = [
  { id: "ZA_skd93kfj", title: "South Africa" },
  { id: "DZ_8sd7f2k3", title: "Algeria" },
  { id: "AO_kdjf93kd", title: "Angola" },
  { id: "BJ_dk3jf8sl", title: "Benin" },
  { id: "BW_kd83jfsl", title: "Botswana" },
  { id: "BF_ld9s7dks", title: "Burkina Faso" },
  { id: "BI_skd84sls", title: "Burundi" },
  { id: "CV_kf74ksld", title: "Cape Verde" },
  { id: "CM_jd84kddl", title: "Cameroon" },
  { id: "CF_sl49skfj", title: "Central African Republic" },
  { id: "TD_dk39dksl", title: "Chad" },
  { id: "KM_kd83ldsl", title: "Comoros" },
  { id: "CG_lsk39dkd", title: "Congo (Brazzaville)" },
  { id: "CD_gjdbvu4vjbjhb", title: "Congo (Kinshasa)" },
  { id: "CI_kd93kdls", title: "Côte d'Ivoire" },
  { id: "DJ_dk3kfj39", title: "Djibouti" },
  { id: "EG_lsl38fjk", title: "Egypt" },
  { id: "GQ_jsl83jfk", title: "Equatorial Guinea" },
  { id: "ER_skd84sld", title: "Eritrea" },
  { id: "SZ_dj93jfls", title: "Eswatini" },
  { id: "ET_kd93kfj4", title: "Ethiopia" },
  { id: "GA_kd84ksld", title: "Gabon" },
  { id: "GM_dj84kfls", title: "Gambia" },
  { id: "GH_kd93jfkd", title: "Ghana" },
  { id: "GN_jdk93kdl", title: "Guinea" },
  { id: "GW_ksl84dks", title: "Guinea-Bissau" },
  { id: "KE_jdk83kdj", title: "Kenya" },
  { id: "LS_dk3kdls9", title: "Lesotho" },
  { id: "LR_skl84dkj", title: "Liberia" },
  { id: "LY_dj49skdj", title: "Libya" },
  { id: "MG_kd94kdls", title: "Madagascar" },
  { id: "MW_jdk48dks", title: "Malawi" },
  { id: "ML_kd84slkd", title: "Mali" },
  { id: "MR_ld93kdsl", title: "Mauritania" },
  { id: "MU_skd84dks", title: "Mauritius" },
  { id: "MA_kd84kdls", title: "Morocco" },
  { id: "MZ_ldk83kfj", title: "Mozambique" },
  { id: "NA_sk39dkfj", title: "Namibia" },
  { id: "NE_jd84kfsl", title: "Niger" },
  { id: "NG_dk93jfkd", title: "Nigeria" },
  { id: "RW_kd84skdj", title: "Rwanda" },
  { id: "ST_jdk84ksl", title: "São Tomé and Príncipe" },
  { id: "SN_kd84kdlz", title: "Senegal" },
  { id: "SC_dj93ksld", title: "Seychelles" },
  { id: "SL_jdk39dks", title: "Sierra Leone" },
  { id: "SO_kd84ksjf", title: "Somalia" },
  { id: "SS_dj38djfk", title: "South Sudan" },
  { id: "SD_kd93kdls", title: "Sudan" },
  { id: "TZ_jdk93kfj", title: "Tanzania" },
  { id: "TG_ksl83ksd", title: "Togo" },
  { id: "TN_dj84kslf", title: "Tunisia" },
  { id: "UG_jdk84sld", title: "Uganda" },
  { id: "ZM_kd84skdj", title: "Zambia" },
  { id: "ZW_jd83kdls", title: "Zimbabwe" },
];

export const southAfricanLanguages = [
  { id: "af", value: "Afrikaans" },
  { id: "en", value: "English" },
  { id: "nr", value: "isiNdebele" },
  { id: "xh", value: "isiXhosa" },
  { id: "zu", value: "isiZulu" },
  { id: "nso", value: "Sepedi" },
  { id: "st", value: "Sesotho" },
  { id: "tn", value: "Setswana" },
  { id: "ss", value: "siSwati" },
  { id: "ve", value: "Tshivenda" },
  { id: "ts", value: "Xitsonga" },
];

export const noteTypeMap = {
  note: "generalNotes",
  "sick-note": "sickNotes",
  prescription: "prescriptions",
};

export const banks = [
  { id: "absa", title: "Absa Bank" },
  { id: "capitec", title: "Capitec Bank" },
  { id: "fnb", title: "FNB (First National Bank)" },
  { id: "nedbank", title: "Nedbank" },
  { id: "standard", title: "Standard Bank" },
  { id: "tyme", title: "TymeBank" },
  { id: "investec", title: "Investec" },
  { id: "african", title: "African Bank" },
];
